esphome:
  name: roller-shutter-2
  friendly_name: Roller_Shutter_2
  on_boot: 
    priority: -100
    then:
      - lambda: |-
          ESP_LOGI("boot", "nun sollte es spät genug sein !?");
          id(rollershutter_2).InitialRun();       

esp32:
  board: esp32dev
  framework:
    type: esp-idf

debug:
  update_interval: 10s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    cpu_frequency:
      name: "CPU Frequency"

# Logger must be at least debug (default)
logger:
  level: debug

api:
  encryption:
    key: !secret encryption_key2

ota:
  - platform: esphome
    password: !secret ota_password2

#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  manual_ip:
    static_ip: 192.168.50.121
    gateway: 192.168.50.2
    subnet: 255.255.255.0
    dns1: 192.168.50.2

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

uart:
  - id: rs485
    tx_pin: GPIO13
    rx_pin: GPIO16
    baud_rate: 9600

i2c:
  sda: GPIO4
  scl:
    number: GPIO5
    ignore_strapping_warning: true

pcf8574:
  - id: inputs_1_8
    address: 0x22
    pcf8575: false
  - id: inputs_9_16
    address: 0x21
    pcf8575: false
  - id: outputs_1_8
    address: 0x24
    pcf8575: false
  - id: outputs_9_16
    address: 0x25
    pcf8575: false

binary_sensor:
  - platform: gpio
    name: "KC868-A16-HT1"
    pin:
      number: GPIO32
      inverted: true

  - platform: gpio
    name: "KC868-A16-HT2"
    pin:
      number: GPIO33
      inverted: true

  - platform: gpio
    name: "KC868-A16-HT3"
    pin:
      number: GPIO14
      inverted: true

  - platform: gpio
    name: "RL_SCH_I_U"
    pin:
      pcf8574: inputs_1_8
      number: 0
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "RL_SCH_I_D"
    pin:
      pcf8574: inputs_1_8
      number: 1
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "RL_GAR_I_U"
    pin:
      pcf8574: inputs_1_8
      number: 2
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "RL_GAR_I_D"
    pin:
      pcf8574: inputs_1_8
      number: 3
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "RL_BA2_I_U"
    pin:
      pcf8574: inputs_1_8
      number: 4
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "RL_BA2_I_D"
    pin:
      pcf8574: inputs_1_8
      number: 5
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "RL_SFN_I_U"
    pin:
      pcf8574: inputs_1_8
      number: 6
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "RL_SFN_I_D"
    pin:
      pcf8574: inputs_1_8
      number: 7
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "RL_SFS_I_U"
    pin:
      pcf8574: inputs_9_16
      number: 0
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "RL_SFS_I_D"
    pin:
      pcf8574: inputs_9_16
      number: 1
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "ZEN_I_U"
    pin:
      pcf8574: inputs_9_16
      number: 2
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "ZEN_I_D"
    pin:
      pcf8574: inputs_9_16
      number: 3
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "URL_I_UD"
    pin:
      pcf8574: inputs_9_16
      number: 4
      mode: INPUT
      inverted: true

switch:
  - platform: gpio
    name: "RL_SCH_O_U"
    pin:
      pcf8574: outputs_1_8
      number: 0
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_SCH_O_D"
    pin:
      pcf8574: outputs_1_8
      number: 1
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_GAR_O_U"
    pin:
      pcf8574: outputs_1_8
      number: 2
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_GAR_O_D"
    pin:
      pcf8574: outputs_1_8
      number: 3
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_BA2_O_U"
    pin:
      pcf8574: outputs_1_8
      number: 4
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_BA2_O_D"
    pin:
      pcf8574: outputs_1_8
      number: 5
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_SFN_O_U"
    pin:
      pcf8574: outputs_1_8
      number: 6
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_SFN_O_D"
    pin:
      pcf8574: outputs_1_8
      number: 7
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_SFS_O_U"
    pin:
      pcf8574: outputs_9_16
      number: 0
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_SFS_O_D"
    pin:
      pcf8574: outputs_9_16
      number: 1
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "HOUSENUMBER"
    pin:
      pcf8574: outputs_9_16
      number: 2
      mode: OUTPUT
      inverted: true

external_components:
  - source: 
      type: git
      url: https://github.com/MarioRosi/esphome
      ref: dev      
    components: [ rollershutter ]
    refresh: 0d

rollershutter:
  id: rollershutter_2
  name: rollershutter_2

  rstimes:
    - id: TIME_NORMAL
      milisecondsup: 20000
      milisecondsdown: 20000
      milisecondsgap: 14000

    - id: TIME_BIGWINDOW
      milisecondsup: 27000
      milisecondsdown: 27000
      milisecondsgap: 17000

    - id: TIME_BIGDOOR
      milisecondsup: 30000
      milisecondsdown: 27000
      milisecondsgap: 11000

  rsgroups:
    - id: HOUSE_SOUTH
      name: haus-sued
      sundowner:
        monthfrom: 5
        monthto: 9
        gaphour: 8
        gapminute: 0
        uphour: 15
        upminute: 45

    - id: HOUSE_NORTH
      name: haus-nord
      sundowner:
        offline: 1

    - id: HOUSE_EAST
      name: haus-ost
      sundowner:
        monthfrom: 5
        monthto: 9
        gaphour: 6
        gapminute: 30
        uphour: 11
        upminute: 00

    - id: HOUSE_WEST
      name: haus-west
      sundowner:
        monthfrom: 5
        monthto: 9
        gaphour: 13
        gapminute: 40
        uphour: 18
        upminute: 55

  rshutterAll:
    allinputup_id: in_zen_u
    allinputdown_id: in_zen_d
    allinputhollyday_id: in_url_ud
    allinput_master: True
    allinput_slave: False

  rshutters:
    - id: rs_sch
      name: schlafzimmer
      rsgroup_id: HOUSE_WEST
      rstime_id: TIME_NORMAL
      inputup_id: rl_sch_i_u
      inputdown_id: rl_sch_i_d
      outputup_id: rl_sch_o_u
      outputdown_id: rl_sch_o_d

    - id: rs_gar
      name: garage
      rsgroup_id: HOUSE_NORTH
      rstime_id: TIME_NORMAL
      inputup_id: rl_gar_i_u
      inputdown_id: rl_gar_i_d
      outputup_id: rl_gar_o_u
      outputdown_id: rl_gar_o_d

    - id: rs_ba2
      name: gad-gross
      rsgroup_id: HOUSE_EAST
      rstime_id: TIME_NORMAL
      inputup_id: rl_ba2_i_u
      inputdown_id: rl_ba2_i_d
      outputup_id: rl_ba2_o_u
      outputdown_id: rl_ba2_o_d

    - id: rs_sfn
      name: stube-nord
      rsgroup_id: HOUSE_EAST
      rstime_id: TIME_NORMAL
      inputup_id: rl_sfn_i_u
      inputdown_id: rl_sfn_i_d
      outputup_id: rl_sfn_o_u
      outputdown_id: rl_sfn_o_d

    - id: rs_sfs
      name: stubesued
      rsgroup_id: HOUSE_EAST
      rstime_id: TIME_NORMAL
      inputup_id: rl_sfs_i_u
      inputdown_id: rl_sfs_i_d
      outputup_id: rl_sfs_o_u
      outputdown_id: rl_sfs_o_d
