# Die Device-Yaml für die Rolladensteuerung
# LAN MAC F0:24:F9:5A:F7:7F
# WIFI MAC F0:24:F9:5A:F7:7C
substitutions:
  mydelay_on: 50ms
  mydelay_off: 300ms

esphome:
  name: roller-shutter-1
  friendly_name: Roller_Shutter_1
  on_boot: 
    priority: -100
    then:
      - lambda: |-          
          id(rollershutter_1).MySetup();
          id(rollershutter_1).InitialRun();

esp32:
  board: esp32dev
  framework:
    type: esp-idf

debug:

# Logger must be at least debug (default)
logger:
  level: DEBUG

api:
  encryption:
    key: !secret encryption_key1

ota:
  - platform: esphome
    password: !secret ota_password1

#wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  manual_ip:
    static_ip: 192.168.50.120
    gateway: 192.168.50.2
    subnet: 255.255.255.0
    dns1: 192.168.50.2

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

uart:
  - id: rs485
    tx_pin: GPIO13
    rx_pin: GPIO16
    baud_rate: 9600

i2c:
  sda: GPIO4
  scl:
    number: GPIO5
    ignore_strapping_warning: true

text_sensor:
  - platform: template
    name: RL_Hausanschluss
  - platform: template
    name: RL_Kueche
  - platform: template
    name: RL_Bad_Kinder
  - platform: template
    name: RL_KiZi_1
  - platform: template
    name: RL_KiZi_2
  - platform: template
    name: RL_Arbeit
  - platform: template
    name: RL_Stube_Ter_Tuer
  - platform: template
    name: RL_Stube_Terrasse

pcf8574:
  - id: inputs_1_8
    address: 0x22
    pcf8575: false
  - id: inputs_9_16
    address: 0x21
    pcf8575: false
  - id: outputs_1_8
    address: 0x24
    pcf8575: false
  - id: outputs_9_16
    address: 0x25
    pcf8575: false

binary_sensor:
  - platform: gpio
    name: "KC868-A16-HT1"
    pin:
      number: GPIO32
      inverted: true

  - platform: gpio
    name: "KC868-A16-HT2"
    pin:
      number: GPIO33
      inverted: true

  - platform: gpio
    name: "KC868-A16-HT3"
    pin:
      number: GPIO14
      inverted: true

  - platform: gpio
    name: "RL_HAR_I_U"
    pin:
      pcf8574: inputs_1_8
      number: 0
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_HAR_I_D"
    pin:
      pcf8574: inputs_1_8
      number: 1
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_KIT_I_U"
    pin:
      pcf8574: inputs_1_8
      number: 2
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_KIT_I_D"
    pin:
      pcf8574: inputs_1_8
      number: 3
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_BA1_I_U"
    pin:
      pcf8574: inputs_1_8
      number: 4
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_BA1_I_D"
    pin:
      pcf8574: inputs_1_8
      number: 5
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_KI1_I_U"
    pin:
      pcf8574: inputs_1_8
      number: 6
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_KI1_I_D"
    pin:
      pcf8574: inputs_1_8
      number: 7
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_KI2_I_U"
    pin:
      pcf8574: inputs_9_16
      number: 0
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_KI2_I_D"
    pin:
      pcf8574: inputs_9_16
      number: 1
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_ARB_I_U"
    pin:
      pcf8574: inputs_9_16
      number: 2
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_ARB_I_D"
    pin:
      pcf8574: inputs_9_16
      number: 3
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_STT_I_U"
    pin:
      pcf8574: inputs_9_16
      number: 4
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_STT_I_D"
    pin:
      pcf8574: inputs_9_16
      number: 5
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_STF_I_U"
    pin:
      pcf8574: inputs_9_16
      number: 6
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

  - platform: gpio
    name: "RL_STF_I_D"
    pin:
      pcf8574: inputs_9_16
      number: 7
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: $mydelay_on
      - delayed_off: $mydelay_off     

switch:
  - platform: gpio
    name: "RL_HAR_O_U"
    pin:
      pcf8574: outputs_1_8
      number: 0
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_HAR_O_D"
    pin:
      pcf8574: outputs_1_8
      number: 1
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_KIT_O_U"
    pin:
      pcf8574: outputs_1_8
      number: 2
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_KIT_O_D"
    pin:
      pcf8574: outputs_1_8
      number: 3
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_BA1_O_U"
    pin:
      pcf8574: outputs_1_8
      number: 4
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_BA1_O_D"
    pin:
      pcf8574: outputs_1_8
      number: 5
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_KI1_O_U"
    pin:
      pcf8574: outputs_1_8
      number: 6
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_KI1_O_D"
    pin:
      pcf8574: outputs_1_8
      number: 7
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_KI2_O_U"
    pin:
      pcf8574: outputs_9_16
      number: 0
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_KI2_O_D"
    pin:
      pcf8574: outputs_9_16
      number: 1
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_ARB_O_U"
    pin:
      pcf8574: outputs_9_16
      number: 2
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_ARB_O_D"
    pin:
      pcf8574: outputs_9_16
      number: 3
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_STT_O_U"
    pin:
      pcf8574: outputs_9_16
      number: 4
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_STT_O_D"
    pin:
      pcf8574: outputs_9_16
      number: 5
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_STF_O_U"
    pin:
      pcf8574: outputs_9_16
      number: 6
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "RL_STF_O_D"
    pin:
      pcf8574: outputs_9_16
      number: 7
      mode: OUTPUT
      inverted: true

external_components:
  - source: 
      type: git
      url: https://github.com/MarioRosi/esphome
      ref: dev
    components: [ rollershutter ]
    refresh: 0d

rollershutter:
  id: rollershutter_1
  name: rollershutter-1

  rstimes:
    - id: TIME_NORMAL
      secondsup: 19.0
      secondsdown: 18.0
      secondsgap: 14.0

    - id: TIME_BIGWINDOW
      secondsup: 24.0
      secondsdown: 22.0
      secondsgap: 17.0

    - id: TIME_BIGDOOR
      secondsup: 27.0
      secondsdown: 28.0
      secondsgap: 17.0

  rsgroups:
    - id: HOUSE_SOUTH
      name: haus-sued
      sundowner:
        monthfrom: 5
        monthto: 9
        gaphour: 8
        gapminute: 0
        uphour: 15
        upminute: 45

    - id: HOUSE_NORTH
      name: haus-nord
      sundowner:
        offline: 1

    - id: HOUSE_EAST
      name: haus-ost
      sundowner:
        monthfrom: 5
        monthto: 9
        gaphour: 6
        gapminute: 30
        uphour: 11
        upminute: 0

    - id: HOUSE_WEST
      name: haus-west
      sundowner:
        monthfrom: 5
        monthto: 9
        gaphour: 13
        gapminute: 40
        uphour: 18
        upminute: 55

  rshutterAll:
    allinputup_id: remote
    allinputdown_id: remote
    allinputhollyday_id: remote
    allinput_master: False
    allinput_slave: True

  rshutters:
    - id: rs_har
      name: hausanschlussraum
      rsgroup_id: HOUSE_SOUTH
      rstime_id: TIME_NORMAL
      inputup_id: rl_har_i_u
      inputdown_id: rl_har_i_d
      outputup_id: rl_har_o_u
      outputdown_id: rl_har_o_d
      display_id: rl_hausanschluss

    - id: rs_kit
      name: kueche
      rsgroup_id: HOUSE_SOUTH
      rstime_id: TIME_NORMAL
      inputup_id: rl_kit_i_u
      inputdown_id: rl_kit_i_d
      outputup_id: rl_kit_o_u
      outputdown_id: rl_kit_o_d
      display_id: rl_kueche

    - id: rs_ba1
      name: kinderbad
      rsgroup_id: HOUSE_SOUTH
      rstime_id: TIME_NORMAL
      inputup_id: rl_ba1_i_u
      inputdown_id: rl_ba1_i_d
      outputup_id: rl_ba1_o_u
      outputdown_id: rl_ba1_o_d
      display_id: rl_bad_kinder

    - id: rs_ki1
      name: kinderzimmer
      rsgroup_id: HOUSE_SOUTH
      rstime_id: TIME_NORMAL
      inputup_id: rl_ki1_i_u
      inputdown_id: rl_ki1_i_d
      outputup_id: rl_ki1_o_u
      outputdown_id: rl_ki1_o_d
      display_id: rl_kizi_1

    - id: rs_ki2
      name: kinder-schlafen
      rsgroup_id: HOUSE_WEST
      rstime_id: TIME_NORMAL
      inputup_id: rl_ki2_i_u
      inputdown_id: rl_ki2_i_d
      outputup_id: rl_ki2_o_u
      outputdown_id: rl_ki2_o_d
      display_id: rl_kizi_2

    - id: rs_arb
      name: arbeitsplatz
      rsgroup_id: HOUSE_WEST
      rstime_id: TIME_NORMAL
      inputup_id: rl_arb_i_u
      inputdown_id: rl_arb_i_d
      outputup_id: rl_arb_o_u
      outputdown_id: rl_arb_o_d
      display_id: rl_arbeit

    - id: rs_stt
      name: stube-terassentuer
      rsgroup_id: HOUSE_WEST
      rstime_id: TIME_BIGDOOR
      inputup_id: rl_stt_i_u
      inputdown_id: rl_stt_i_d
      outputup_id: rl_stt_o_u
      outputdown_id: rl_stt_o_d
      display_id: rl_stube_ter_tuer

    - id: rs_stf
      name: stube-terassenfenster
      rsgroup_id: HOUSE_WEST
      rstime_id: TIME_BIGWINDOW
      inputup_id: rl_stf_i_u
      inputdown_id: rl_stf_i_d
      outputup_id: rl_stf_o_u
      outputdown_id: rl_stf_o_d
      display_id: rl_stube_terrasse
